In [1]:
# When multiple series are combined then this becomes a data frame.
# Data frame can be created from a dictionary and a list.

In [2]:
import numpy as np
import pandas as pd

In [3]:
#Creating Data Frame

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
# Selection and Indexing of Columns

In [24]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [25]:
df2[["City", "Name"]]

       City   Name
0  New York   John
1     Paris   Anna
2    Berlin  Peter
3    London  Linda

In [26]:
# Creating a new column
df2["Designation"] = ["Engineer", "Doctor", "Plumber", "Pilot"]

In [27]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000      Doctor
2  Peter   29    Berlin   62000     Plumber
3  Linda   42    London   85000       Pilot

In [28]:
# Removing a column
# Below is the snapshoot, column is still in the main data
df2.drop("Designation", axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000      Doctor
2  Peter   29    Berlin   62000     Plumber
3  Linda   42    London   85000       Pilot

In [30]:
# For deleting completly
df2.drop("Designation",axis=1,inplace=True)

In [33]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [34]:
df2.drop(["Salary", "City"],axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [35]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [36]:
# Removing Rows same as removing columns just gave axis 0
df2.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [37]:
df2.drop([1,2],axis=0)

    Name  Age      City  Salary
0   John   28  New York   65000
3  Linda   42    London   85000

In [47]:
# Selecting Rows
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [54]:
# Selecting both rows and columns

In [57]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [58]:
df.loc[[2,3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [53]:
# Conditional Selection

In [59]:
# Only wants to see those people whose age is above 30

In [74]:
df2[df2["Age"] > 30 ]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [75]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000