In [6]:
import numpy as np 
import pandas as pd

In [3]:
# Loading data

In [8]:
#make a new column for episode count
#make a new column for time stamp
#which anime has the highest score
#give me top 5 highest scoring anime
#which anime has the highest episode count
#animes with top 5 episode count
#which is the longest running anime

In [9]:
df = pd.read_csv(r'anime.csv')

In [69]:
df.head()  #head fuction displays the top 5 rows of the data

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

In [70]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [71]:
def extractEpisodes(txt):
    check = False
    data = ""
    for i in txt:
        if i == ")":
            check = False
            return data
        if check == True:
            data = data + i
        if i == "(":
            check = True

In [72]:
df["Episodes"] = df['Title'].apply(extractEpisodes)  #apply runs on all the rows of data

In [73]:
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

In [78]:
df["Episodes"] = df["Episodes"].str.replace(" eps","")

In [79]:
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

In [87]:
type(df.loc[0]['Episodes']) #For type checking

numpy.int64

In [88]:
df["Episodes"] = df["Episodes"].astype(int) #data type changed

In [89]:
type(df.loc[0]['Episodes'])

numpy.int64